# Generated by Django 3.0.5 on 2020-05-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=64)),
                ('text', models.FileField(upload_to='text_files/')),
            ],
        ),
    ]
