# Generated by Django 3.0.5 on 2020-04-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200429_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nominal',
            field=models.CharField(default='€/Stk.', max_length=10),
            preserve_default=False,
        ),
    ]
